[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Ensure a modern Node for tooling; Netlify defaults may be older.
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
